In [8]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [23]:
con = mysql.connector.connect(host='localhost',
                               user = 'root',
                               password = 'root',
                               database = 'rajan2')

In [24]:
engine = create_engine('mysql+mysqlconnector://root:root@localhost/rajan2')

In [25]:
df = pd.read_csv('ipl.csv')
df.head(2)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals

In [26]:
df.to_sql(
    name = 'ipl',
    con = engine,
    if_exists='replace', #use "append" if table already exists
    index=False
)
print("Data uploded successfully!")

Data uploded successfully!

In [27]:
df.to_sql(
    name="ipl_ball_by_ball",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

225954

In [33]:
import pandas as pd

query = "SELECT COUNT(*) FROM ipl"
pd.read_sql(query, con=engine)

   COUNT(*)
0    225954

In [34]:
pd.read_sql("SELECT * FROM ipl LIMIT 10", con=engine)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,None,0,0,0,0,0,None,None,None,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,None,None,None,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,None,1,0,1,0,0,None,None,None,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,None,0,0,0,0,0,None,None,None,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,None,0,0,0,0,0,None,None,None,Rajasthan Royals
5,1312200,1,0,6,YBK Jaiswal,Mohammed Shami,JC Buttler,None,0,0,0,0,0,None,None,None,Rajasthan Royals
6,1312200,1,1,1,JC Buttler,Yash Dayal,YBK Jaiswal,None,0,0,0,0,0,None,None,None,Rajasthan Royals
7,1312200,1,1,2,JC Buttler,Yash Dayal,YBK Jaiswal,None,0,0,0,0,0,None,None,None,Rajasthan Royals
8,1312200,1,1,3,JC Buttler,Yash Dayal,YBK Jaiswal,None,4,0,4,0,0,None,None,None,Rajasthan Royals
9,1312200,1,1,4,JC Buttler,Yash Dayal,YBK Jaiswal,None,0,0,0,0,0,None,None,None,Rajasthan Royals

In [36]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:root@localhost/rajan2"
)

In [37]:
# Find Top 5 Batsmen in IPL (by total runs)
query = """
SELECT batter,
       SUM(batsman_run) AS total_runs
FROM ipl
GROUP BY batter
ORDER BY total_runs DESC
LIMIT 5;
"""

top_5_batsmen = pd.read_sql(query, con=engine)
top_5_batsmen

      batter  total_runs
0    V Kohli      6634.0
1   S Dhawan      6244.0
2  DA Warner      5883.0
3  RG Sharma      5881.0
4   SK Raina      5536.0

In [38]:
# Find 2nd Highest Six Hitter in IPL
query = """
SELECT batter,
       COUNT(*) AS sixes
FROM ipl
WHERE batsman_run = 6
GROUP BY batter
ORDER BY sixes DESC
LIMIT 1 OFFSET 1;
"""

second_highest_six_hitter = pd.read_sql(query, con=engine)
second_highest_six_hitter

           batter  sixes
0  AB de Villiers    253

In [39]:
# Virat Kohli’s Performance (Overall since team info not available)
query = """
SELECT batter,
       SUM(batsman_run) AS total_runs,
       COUNT(*) AS balls_faced,
       ROUND(SUM(batsman_run)/COUNT(*)*100, 2) AS strike_rate
FROM ipl
WHERE batter = 'V Kohli'
GROUP BY batter;
"""

virat_kohli_performance = pd.read_sql(query, con=engine)
virat_kohli_performance

    batter  total_runs  balls_faced  strike_rate
0  V Kohli      6634.0         5266       125.98

In [40]:
# Find Top 10 Batsmen with Centuries in IPL
query = """
SELECT batter,
       COUNT(*) AS centuries
FROM (
    SELECT ID, batter, SUM(batsman_run) AS runs
    FROM ipl
    GROUP BY ID, batter
    HAVING runs >= 100
) AS century_table
GROUP BY batter
ORDER BY centuries DESC
LIMIT 10;
"""

top_10_centuries = pd.read_sql(query, con=engine)
top_10_centuries

           batter  centuries
0        CH Gayle          6
1      JC Buttler          5
2         V Kohli          5
3       DA Warner          4
4        KL Rahul          4
5       SR Watson          4
6       SV Samson          3
7  AB de Villiers          3
8       Q de Kock          2
9         HM Amla          2

In [41]:
# Top 5 Batsmen with Highest Strike Rate
query = """
SELECT batter,
       COUNT(*) AS balls_faced,
       SUM(batsman_run) AS runs,
       ROUND(SUM(batsman_run)/COUNT(*)*100, 2) AS strike_rate
FROM ipl
GROUP BY batter
HAVING balls_faced >= 1000
ORDER BY strike_rate DESC
LIMIT 5;
"""

top_strike_rate_batsmen = pd.read_sql(query, con=engine)
top_strike_rate_batsmen

           batter  balls_faced    runs  strike_rate
0      AD Russell         1212  2039.0       168.23
1        V Sehwag         1833  2728.0       148.83
2  AB de Villiers         3487  5181.0       148.58
3      GJ Maxwell         1571  2320.0       147.68
4      JC Buttler         1955  2832.0       144.86

In [1]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [2]:
con = mysql.connector.connect(host='localhost',
                               user = 'root',
                               password = 'root',
                               database = 'flipcart')

In [3]:
engine = create_engine('mysql+mysqlconnector://root:root@localhost/flipcart')

In [6]:
df = pd.read_sql("SELECT * FROM orders", con=engine)
df.head()

  order_id  user_id  order_date
0  B-25601        1  01-04-2018
1  B-26011        1  12-02-2019
2  B-26074        1  21-03-2019
3  B-25602        2  01-04-2018
4  B-26012        2  13-02-2019

In [10]:
pd.read_sql("SHOW TABLES", con=engine)

  Tables_in_flipcart
0           category
1      order_details
2             orders
3              users

In [13]:
pd.read_sql("DESCRIBE orders", con=engine)

        Field  Type Null Key Default Extra
0    order_id  text  YES        None
1     user_id   int  YES        None
2  order_date  text  YES        None

In [14]:
query = """
SELECT 
    o.order_id,
    o.user_id,
    u.state,
    o.order_date
FROM orders o
JOIN users u
    ON o.user_id = u.user_id
"""

df = pd.read_sql(query, con=engine)
df.head()

  order_id  user_id        state  order_date
0  B-25601        1      Gujarat  01-04-2018
1  B-26011        1      Gujarat  12-02-2019
2  B-26074        1      Gujarat  21-03-2019
3  B-25602        2  Maharashtra  01-04-2018
4  B-26012        2  Maharashtra  13-02-2019

In [18]:
df = pd.read_sql(query, con=engine)
df.head()

  order_id  user_id        state  order_date
0  B-25601        1      Gujarat  01-04-2018
1  B-26011        1      Gujarat  12-02-2019
2  B-26074        1      Gujarat  21-03-2019
3  B-25602        2  Maharashtra  01-04-2018
4  B-26012        2  Maharashtra  13-02-2019

In [21]:
query = """
SELECT *
FROM orders
WHERE profit > 0;
"""

In [22]:
query = """
SELECT customer_id,
       customer_name,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id, customer_name
ORDER BY total_orders DESC
LIMIT 1;
"""